<html>
	
		<title>FMCG</title>
	<style>
	<?php include_once 'assets/css/fmcg.css';?>
	</style>
	<body>
		<?php include_once 'layout/head.php';?>
		<?php include_once 'layout/header.php';?>
		<div class="title">
<h1>FMCG</h1>
<hr>
</div>
<div class="first">
<div class="container">
	
	<div class="row">
		<div class="col-sm-6">
		<p>
			Fast-moving consumer goods (FMCG) sector is the 4th largest sector in the Indian economy with Household and Personal Care accounting for 50 per cent of FMCG sales in India. Growing awareness, easier access and changing lifestyles have been the key growth drivers for the sector. The urban segment (accounts for a revenue share of around 55 per cent) is the largest contributor to the overall revenue generated by the FMCG sector in India. However, in the last few years, the FMCG market has grown at a faster pace in rural India compared with urban India. Semi-urban and rural segments are growing at a rapid pace and FMCG products account for 50 per cent of total rural spending.<br>

			The retail market in India is estimated to reach US$ 1.1 trillion by 2020 from US$ 840 billion in 2017, with modern trade expected to grow at 20 per cent - 25 per cent per annum, which is likely to boost revenues of FMCG companies. </p>
		</div>
<div class="col-sm-6">
		<img src="assets/images/fmcg3.jpg">
	</div>
	</div>
	<p>
	Revenues of FMCG sector reached Rs 3.4 lakh crore (US$ 52.75 billion) in FY18 and are estimated to reach US$ 103.7 billion in 2020. The sector witnessed growth of 16.5 per cent in value terms between July-September 2018; supported by moderate inflation, increase in private consumption and rural income.</p>
</div>
	<div class="secondd">
		<hr>
		<h1>Specialities</h1>
	</div>
<section class="technologies">
		<div class="container">
		<div class="row">
			<div class="col-sm-3">
				<div class="left-image">
				<img src="assets/images/fmcg2.png">
			</div>
			</div>
			<div class="col-sm-9">
				<div class="right-slide">
    <div class="ct-row">
      <div class="ct-current-facts__slider ct-js-current-facts__slider">
        
        <div class="item">
          <div class="ct-current-fact"><h3>Personal care</h3></div>
        </div>
        <div class="item">
          <div class="ct-current-fact"><h3>Food and Beverages</h3></div>
        </div>
        <div class="item">
          <div class="ct-current-fact"><h3>Household Care</h3></div>
        </div>
        <div class="item">
          <div class="ct-current-fact"><h3>Multi Level Marketing</div>
        </div>
        <div class="item">
          <div class="ct-current-fact"><h3>Nutrition companies</h3></div>
        </div>
      </div>
    </div>
  </div>
</div>
  </div>	
</section>

<div class="auto3">
	<div class="container">
	<h1>Fastest Jobs Team of Specialists</h1>
		<div class="row">
			<div class="col-sm-3">
				<div class="auto31">
					<p>Over the years, we have successfully executed various client assignments and stayed ahead of the curve in the Automobile domain. We have a commendable record of timely delivery of services in the most challenging atmosphere in talent recruitment in the Automobile & Auto Components’ sector. We believe in maintaining long-standing relationships with our clients and ensure that companies find a perfect link with the right talent at the right time.	</p>
				</div>	
			</div>
			
			<div class="col-sm-3">
				<div class="auto32">
				<img src="assets/images/face1.jpg">
				<div class="auto33">
				<a href="https://www.linkedin.com/home">
					<i class="fa fa-linkedin-square"></i>
				</a>
				<a href="https://gmail.com" style="color:grey;">
					<i class="fa fa-envelope"></i>
				</a>				
				</div>
					<p></p>
				</div>
				<div class="auto32">
				<img src="assets/images/face1.jpg">
				<div class="auto33">
				<a href="https://www.linkedin.com/home">
					<i class="fa fa-linkedin-square"></i>
				</a>
				<a href="https://gmail.com" style="color:grey;">
					<i class="fa fa-envelope"></i>
				</a>				
				</div>
					<p></p>
				</div>
			</div>	
			<div class="col-sm-6">
				<div class="auto34">
					<h1>Mukesh Vats</h1>
					<h4>Vertical Head</h4>
					<p>Mukesh Vats take the full responsibility of autospace & Defense Department as he kis highly aware of this department having marvellous knowledge about these things and highly aware about the future aspects in this modern and civilised world.</p>
					
				
				</div>
				<div class="auto34">
					<h1>Aakash Gaur</h1>
					<h4>Auto Head</h4>
					<p>Aakash Gaur take the full responsibility of autospace & Defense Department as he kis highly aware of this department having marvellous knowledge about these things and highly aware about the future aspects in this modern and civilised world.</p>
					
				
				</div>
			</div>	
			
			
			
		</div>
	</div>
	<div class="box" >
		<div class="container">
		<div class="row">
			<div class="col-sm-3">
				<img src="assets/images/search.png">
			</div>
			<div class="col-sm-9">
				<p>
					Our selection process is based on a structured and systematic approach, which is proactive, detailed and target oriented. This process begins with understanding the clients’ needs and goes all the way to follow-up with both clients and candidates post recruitment.</p>
 <div class="button">
    <input type="submit" class="btn btn-info" value="SEARCH METHODOLGY" >
</div>
</div></div>
		</div>
		</div>
</div>

<div class="representative">
	<div class="container">
		<h3>Representative Searches</h3><br>
		<div class="row">
			<div class="col-sm-4">
				

					<ul>Country Manager,<br>
                        Engineering Company,

					</ul>
					<ul>Managing Director-India,
						<br>Flavors and Fragrances Manufacturer
                    </ul>
                    <ul>Chief Executive Officer,
						<br>Hydraulic and General Purpose Industrial Hoses
						<br> Manufacturer
                    </ul>
                     <ul>Finance Controller,
					<br>Industrial Adhesives Manufacturer
                    </ul>
                     <ul>Director-OH&S,
                     <br>Cement Manufacturer
                    </ul>
                     <ul>Business Director,
                     <br>Industrial Chemical Manufacturer
               </ul>
       </div>


       <div class="col-sm-4">
       	<div class="border-left">
       	<ul>Plant Director,
      	<br>Cement Manufacturer
               </ul>
            <ul>Vice President,
			<br>Fluid Control Systems Manufacturer
            </ul>
            <ul>General Manager-Head of Sales SR,
			<br>Food Products Machinery Manufacturer
            </ul>
            <ul>General Manager-Marketing,
            <br>Hydraulic Lubricants Manufacturer
               </ul>
            <ul>Site Head,
			<br>Polyster and Industrial Chemical Manufacturer
            </ul>
       </div>
   </div>
       <div class="col-sm-4">
       	<div class="border-left">
       	    <ul>Head-Corporate Affairs,
			<br>Optical Fibre Cable Manufacturer
       	    	</ul>
       	    <ul>Head-Sales and Marketing,
			<br>Horticulture Company</ul>
            <ul>Head Business Excellence,<br>
                Cement Manufacturer
            </ul>
<ul>
	National Sales Manager-Polyolefin<br>
 	Catalysts and Absorbents,<br>
	Industrial Chemical Manufacturer</ul>
<ul>Commercial Manager-Performance<br>
 Solutions,<br>
Industrial Chemical Manufacturer</ul>
</div>
</div>                        


</div>
</div>
</div>
</div>
</div>
<script>
'use strict';
(function($) {
  $('document').ready(function() {

    if ('.ct-js-current-facts__slider'.length) {
      $('.ct-js-current-facts__slider').slick({
        arrows: false,
        slidesToShow: 4,
		loop: true,
        autoplay: true,
		interval: 10,
   
      });
    }

  });

})(jQuery);
</script>

<?php include_once 'layout/footer.php';?>
</body>
</html>

